#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# Tempris MVP — One-command local setup script
# Usage:  chmod +x setup.sh && ./setup.sh
# ─────────────────────────────────────────────────────────────────────
set -e

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BOLD}╔══════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║       Tempris MVP — Local Setup          ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════╝${NC}"
echo ""

# ── 1. Check Python ──────────────────────────────────────────────────
echo -e "${BOLD}[1/5] Checking Python...${NC}"
if command -v python3 &>/dev/null; then
    PY=python3
elif command -v python &>/dev/null; then
    PY=python
else
    echo -e "${RED}✗ Python 3.11+ is required but not found.${NC}"
    echo "  Install from: https://www.python.org/downloads/"
    exit 1
fi

PY_VER=$($PY --version 2>&1 | awk '{print $2}')
echo -e "${GREEN}✓ Found $PY ($PY_VER)${NC}"

# ── 2. Create virtualenv ────────────────────────────────────────────
echo ""
echo -e "${BOLD}[2/5] Setting up Python virtual environment...${NC}"
cd app/backend
if [ ! -d "venv" ]; then
    $PY -m venv venv
    echo -e "${GREEN}✓ Created venv${NC}"
else
    echo -e "${YELLOW}→ venv already exists, skipping${NC}"
fi

# Activate
if [ -f "venv/bin/activate" ]; then
    source venv/bin/activate
elif [ -f "venv/Scripts/activate" ]; then
    source venv/Scripts/activate
fi

# ── 3. Install dependencies ─────────────────────────────────────────
echo ""
echo -e "${BOLD}[3/5] Installing Python dependencies...${NC}"
pip install --quiet -r requirements.txt
echo -e "${GREEN}✓ Dependencies installed${NC}"

# ── 4. Create .env files if missing ─────────────────────────────────
echo ""
echo -e "${BOLD}[4/5] Setting up environment files...${NC}"
cd ../..

# Backend .env
if [ ! -f "app/deploy/.env" ]; then
    cat > app/deploy/.env <<'ENV'
# Tempris Local Dev Secrets (auto-generated by setup.sh)
DATABASE_URL=sqlite:///./tempris.db
JWT_SECRET_KEY=dev_secret_key_change_in_prod_NEVER_USE_IN_PRODUCTION
FREELLM_API_KEY=
FREELLM_BASE_URL=http://localhost:3001/v1
CORS_ORIGINS=http://localhost:5173,http://localhost:8000
ENABLE_HSTS=false
ENV
    echo -e "${GREEN}✓ Created app/deploy/.env (SQLite + dev defaults)${NC}"
else
    echo -e "${YELLOW}→ app/deploy/.env already exists, skipping${NC}"
fi

# FreeLLMAPI .env
if [ ! -f "app/freellmapi/.env" ]; then
    cat > app/freellmapi/.env <<'ENV'
ENCRYPTION_KEY=dev_only_encryption_key_replace_in_production
PORT=3001
ENV
    echo -e "${GREEN}✓ Created app/freellmapi/.env${NC}"
else
    echo -e "${YELLOW}→ app/freellmapi/.env already exists, skipping${NC}"
fi

# ── 5. Start the backend ────────────────────────────────────────────
echo ""
echo -e "${BOLD}[5/5] Starting Tempris backend...${NC}"
echo ""
echo -e "${BOLD}═══════════════════════════════════════════${NC}"
echo -e "${GREEN}  Tempris will start at: http://localhost:8000${NC}"
echo ""
echo -e "  Login credentials:${NC}"
echo -e "  ┌────────────────────────┬──────────┬────────────┐"
echo -e "  │ Email                  │ Password │ Role       │"
echo -e "  ├────────────────────────┼──────────┼────────────┤"
echo -e "  │ sherie@tempris.com     │ demo     │ Superadmin │"
echo -e "  │ admin@tempris.com      │ demo     │ Admin      │"
echo -e "  │ analyst@tempris.com    │ demo     │ Analyst    │"
echo -e "  │ viewer@tempris.com     │ demo     │ Viewer     │"
echo -e "  │ readonly@tempris.com   │ demo     │ Read-only  │"
echo -e "  └────────────────────────┴──────────┴────────────┘"
echo ""
echo -e "${YELLOW}  Note: AI chat (SPEAK/SPOTLIGHT) will use mock responses.${NC}"
echo -e "${YELLOW}  Scanner module requires nmap+nuclei installed locally.${NC}"
echo -e "${BOLD}═══════════════════════════════════════════${NC}"
echo ""

# Export env vars and start
export DATABASE_URL="sqlite:///./tempris.db"
export JWT_SECRET_KEY="dev_secret_key_change_in_prod_NEVER_USE_IN_PRODUCTION"
export FREELLM_API_KEY=""
export FREELLM_BASE_URL="http://localhost:3001/v1"
export CORS_ORIGINS="http://localhost:5173,http://localhost:8000"
export ENABLE_HSTS="false"

cd app/backend
$PY index.py
