# ─────────────────────────────────────────────────────────────────────
# Tempris MVP — One-command local setup script (Windows PowerShell)
# Usage:  .\setup.ps1
# ─────────────────────────────────────────────────────────────────────
$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "╔══════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║       Tempris MVP — Local Setup          ║" -ForegroundColor Cyan
Write-Host "╚══════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# ── 1. Check Python ──────────────────────────────────────────────────
Write-Host "[1/5] Checking Python..." -ForegroundColor White
$py = $null
foreach ($cmd in @("python", "python3", "py")) {
    try {
        $ver = & $cmd --version 2>&1
        if ($ver -match "Python 3\.") {
            $py = $cmd
            Write-Host "  OK Found $ver" -ForegroundColor Green
            break
        }
    } catch {}
}
if (-not $py) {
    Write-Host "  ERROR: Python 3.11+ is required but not found." -ForegroundColor Red
    Write-Host "  Install from: https://www.python.org/downloads/"
    exit 1
}

# ── 2. Create virtualenv ────────────────────────────────────────────
Write-Host ""
Write-Host "[2/5] Setting up Python virtual environment..." -ForegroundColor White
Push-Location app\backend
if (-not (Test-Path "venv")) {
    & $py -m venv venv
    Write-Host "  OK Created venv" -ForegroundColor Green
} else {
    Write-Host "  -> venv already exists, skipping" -ForegroundColor Yellow
}

# Activate
if (Test-Path "venv\Scripts\Activate.ps1") {
    . .\venv\Scripts\Activate.ps1
}
Pop-Location

# ── 3. Install dependencies ─────────────────────────────────────────
Write-Host ""
Write-Host "[3/5] Installing Python dependencies..." -ForegroundColor White
Push-Location app\backend
pip install -q -r requirements.txt
Write-Host "  OK Dependencies installed" -ForegroundColor Green
Pop-Location

# ── 4. Create .env files if missing ─────────────────────────────────
Write-Host ""
Write-Host "[4/5] Setting up environment files..." -ForegroundColor White

if (-not (Test-Path "app\deploy\.env")) {
    @"
# Tempris Local Dev Secrets (auto-generated by setup.ps1)
DATABASE_URL=sqlite:///./tempris.db
JWT_SECRET_KEY=dev_secret_key_change_in_prod_NEVER_USE_IN_PRODUCTION
FREELLM_API_KEY=
FREELLM_BASE_URL=http://localhost:3001/v1
CORS_ORIGINS=http://localhost:5173,http://localhost:8000
ENABLE_HSTS=false
"@ | Set-Content -Path "app\deploy\.env" -Encoding UTF8
    Write-Host "  OK Created app\deploy\.env (SQLite + dev defaults)" -ForegroundColor Green
} else {
    Write-Host "  -> app\deploy\.env already exists, skipping" -ForegroundColor Yellow
}

if (-not (Test-Path "app\freellmapi\.env")) {
    @"
ENCRYPTION_KEY=dev_only_encryption_key_replace_in_production
PORT=3001
"@ | Set-Content -Path "app\freellmapi\.env" -Encoding UTF8
    Write-Host "  OK Created app\freellmapi\.env" -ForegroundColor Green
} else {
    Write-Host "  -> app\freellmapi\.env already exists, skipping" -ForegroundColor Yellow
}

# ── 5. Start the backend ────────────────────────────────────────────
Write-Host ""
Write-Host "[5/5] Starting Tempris backend..." -ForegroundColor White
Write-Host ""
Write-Host "═══════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  Tempris will start at: http://localhost:8000" -ForegroundColor Green
Write-Host ""
Write-Host "  Login credentials:"
Write-Host "  Email                   Password  Role"
Write-Host "  ─────────────────────── ──────── ───────────"
Write-Host "  sherie@tempris.com      demo     Superadmin"
Write-Host "  admin@tempris.com       demo     Admin"
Write-Host "  analyst@tempris.com     demo     Analyst"
Write-Host "  viewer@tempris.com      demo     Viewer"
Write-Host "  readonly@tempris.com    demo     Read-only"
Write-Host ""
Write-Host "  Note: AI chat (SPEAK/SPOTLIGHT) will use mock responses." -ForegroundColor Yellow
Write-Host "  Scanner module requires nmap+nuclei installed locally." -ForegroundColor Yellow
Write-Host "═══════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

$env:DATABASE_URL = "sqlite:///./tempris.db"
$env:JWT_SECRET_KEY = "dev_secret_key_change_in_prod_NEVER_USE_IN_PRODUCTION"
$env:FREELLM_API_KEY = ""
$env:FREELLM_BASE_URL = "http://localhost:3001/v1"
$env:CORS_ORIGINS = "http://localhost:5173,http://localhost:8000"
$env:ENABLE_HSTS = "false"

Push-Location app\backend
& $py index.py
Pop-Location
