-- Migration 024: Chapter 5 platform hardening (PRD-000 Chapter 5, Target
-- architecture items 2 and 4): persisted sessions with per-token revocation,
-- and the tamper-evident audit hash chain.
--
-- 1. user_sessions — V1's UserSession pattern ported onto V2. Every token
--    minted by /api/auth/login persists a session row keyed by the SHA-256 of
--    the token's `jti` claim (the raw jti is never stored). Per-request
--    verification resolves the session and refuses revoked/expired tokens
--    immediately — per-token revocation alongside the existing coarse
--    user/tenant/membership disable (auth.py point-join).
--    Refresh-vs-relogin decision (PRD Ch.5 open decision #1, decided here for
--    v1): explicit 1-hour re-login, NO refresh tokens. The session store is
--    the extension point if refresh is ever productized.
-- 2. audit_events chain columns — prev_hash / entry_hash / hmac_key_id make
--    the audit log tamper-evident (V1's hash chain + verify endpoint, ported).
--    Existing rows are backfilled under the `plain:` scheme (deterministic
--    SHA-256, pgcrypto); new writes from app/audit.py use the
--    `hmac:<key_id>:` scheme (HMAC-SHA256 over the canonical entry, with V1's
--    fail-closed ≥32-char key gate). GET /api/audit/verify recomputes the
--    per-tenant chain and reports the first break.
--
-- Forward-only; the whole file runs inside one transaction (runner.py).

-- SHA-256 for the plain-scheme backfill (bootstrap superuser grants this in
-- the canonical/test containers; a restricted deploy role must be granted
-- pgcrypto before applying this migration).
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------------
-- 1. Persisted sessions / per-token revocation
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS user_sessions (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id           UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    tenant_id         UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    -- SHA-256 hex of the token `jti` claim; the raw jti lives only in the token.
    jti_hash          TEXT NOT NULL UNIQUE CHECK (length(btrim(jti_hash)) = 64),
    issued_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Aligned with the token lifetime (exp - iat = 3600): a session never
    -- outlives its token and vice versa.
    expires_at        TIMESTAMPTZ NOT NULL,
    revoked_at        TIMESTAMPTZ,
    revoking_actor    TEXT,
    revocation_reason TEXT,
    CONSTRAINT ck_user_sessions_lifetime CHECK (expires_at > issued_at),
    CONSTRAINT ck_user_sessions_revoked_shape CHECK (
        (revoked_at IS NULL AND revoking_actor IS NULL AND revocation_reason IS NULL)
        OR (revoked_at IS NOT NULL AND revoking_actor IS NOT NULL
            AND length(btrim(revocation_reason)) > 0)
    )
);

CREATE INDEX IF NOT EXISTS idx_user_sessions_user_active
    ON user_sessions (user_id, tenant_id) WHERE revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_user_sessions_expired
    ON user_sessions (expires_at) WHERE revoked_at IS NULL;

-- ---------------------------------------------------------------------------
-- 2. Audit hash chain
-- ---------------------------------------------------------------------------

ALTER TABLE audit_events
    ADD COLUMN IF NOT EXISTS prev_hash TEXT,
    ADD COLUMN IF NOT EXISTS entry_hash TEXT,
    ADD COLUMN IF NOT EXISTS hmac_key_id TEXT,
    -- Monotonic append order for the chain walk. (created_at, id) alone is
    -- not a safe total order: created_at quantization can tie a Python
    -- writer clock with the DB transaction clock, and id is a random UUID.
    ADD COLUMN IF NOT EXISTS chain_seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Chain walk ordering (must match app/audit.py verification exactly):
-- per tenant, ordered by chain_seq.
CREATE INDEX IF NOT EXISTS idx_audit_events_chain
    ON audit_events (tenant_id, chain_seq);

-- Chain linearity, enforced by the DB: at most ONE entry per tenant may
-- chain from any given prev_hash. Two concurrent appends reading the same
-- predecessor cannot both commit — the loser gets a unique violation and
-- retries from its savepoint (app/audit.py), so the chain can never fork
-- and no advisory lock serializes audit writers (deadlock-free).
CREATE UNIQUE INDEX IF NOT EXISTS uq_audit_events_chain_fork
    ON audit_events (tenant_id, prev_hash);

-- Backfill the sequence for rows that predate it, in (created_at, id) order.
WITH backlog AS (
    SELECT id FROM audit_events WHERE chain_seq IS NULL ORDER BY created_at, id
)
UPDATE audit_events e
SET chain_seq = nextval(pg_get_serial_sequence('audit_events', 'chain_seq'))
FROM backlog b
WHERE e.id = b.id;

-- Backfill: chain every pre-existing row per tenant under the `plain:`
-- scheme. canonical row string (mirrored verbatim by app/audit.py for
-- verification — this is the SCHEME CONTRACT, edit neither side alone):
--   tenant_id|actor_id|actor_role|event_name|asset_id-or-''|details::text|
--   created_at-as-UTC-'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'|prev_hash
-- entry_hash = 'plain:' || sha256_hex(canonical). First row of a tenant
-- chains from the genesis prev_hash '0'.
WITH RECURSIVE ordered AS (
    SELECT id, tenant_id, actor_id, actor_role, event_name, asset_id, details,
           created_at,
           ROW_NUMBER() OVER (PARTITION BY tenant_id ORDER BY created_at, id) AS rn
    FROM audit_events
    WHERE entry_hash IS NULL
),
chained AS (
    SELECT o.rn, o.id, o.tenant_id,
           '0'::text AS prev_hash,
           'plain:' || encode(digest(
               format('%s|%s|%s|%s|%s|%s|%s|%s',
                      o.tenant_id, o.actor_id, o.actor_role, o.event_name,
                      COALESCE(o.asset_id::text, ''), o.details::text,
                      to_char(o.created_at AT TIME ZONE 'UTC',
                              'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),
                      '0'),
               'sha256'), 'hex') AS entry_hash
    FROM ordered o
    WHERE o.rn = 1

    UNION ALL

    SELECT o.rn, o.id, o.tenant_id,
           c.entry_hash AS prev_hash,
           'plain:' || encode(digest(
               format('%s|%s|%s|%s|%s|%s|%s|%s',
                      o.tenant_id, o.actor_id, o.actor_role, o.event_name,
                      COALESCE(o.asset_id::text, ''), o.details::text,
                      to_char(o.created_at AT TIME ZONE 'UTC',
                              'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),
                      c.entry_hash),
               'sha256'), 'hex') AS entry_hash
    FROM ordered o
    JOIN chained c ON c.tenant_id = o.tenant_id AND c.rn = o.rn - 1
)
UPDATE audit_events e
SET prev_hash = c.prev_hash,
    entry_hash = c.entry_hash
FROM chained c
WHERE e.id = c.id;
