# backend/tests/test_vuln_intelligence.py
"""
Contract tests for the Vulnerability Intelligence Core — Sprint 01.

These tests cover:
  - Identity, lifecycle, exact-link semantics (rubric weight 20)
  - Provenance and multi-assessment preservation (rubric weight 15)
  - CVSS/TES resolver correctness (rubric weight 15)
  - Atomic synchronization and idempotency (rubric weight 20)
  - Content-addressed revision deduplication
  - OSV alias separation
  - KEV and EPSS enrichment
  - Sync state and snapshot lifecycle

All tests run offline against checked-in fixtures and a local PostgreSQL 17
database. No network calls.
"""
import json
import uuid
from datetime import date, datetime, timezone
from decimal import Decimal
from pathlib import Path

import pytest

from app.db import get_db_connection
from app.vuln_intelligence.models import (
    CanonicalVulnerability,
    CvssAssessment,
    CveRelationship,
    CveAffected,
    CveAdpEntry,
    EpssScore,
    KevEntry,
    OsvAlias,
    OsvRecord,
    SourceRecord,
    SyncSnapshot,
    SyncState,
    validate_cve_id,
)
from app.vuln_intelligence.repository import (
    content_hash,
    upsert_canonical_vulnerability,
    get_canonical_vulnerability,
    upsert_source_record,
    get_current_source_record,
    get_source_record_revisions,
    upsert_cvss_assessment,
    get_cvss_assessments,
    resolve_tes_cvss,
    upsert_cve_relationship,
    get_cve_relationships,
    upsert_cve_affected,
    get_cve_affected,
    upsert_adp_entry,
    get_adp_entries,
    upsert_kev_entry,
    get_kev_entry,
    upsert_epss_score,
    get_epss_scores,
    upsert_osv_record,
    get_osv_record,
    upsert_osv_alias,
    get_osv_aliases,
    get_osv_records_by_cve,
    create_sync_snapshot,
    complete_sync_snapshot,
    get_sync_snapshot,
    get_sync_state,
    update_sync_state,
    get_all_sync_states,
    upsert_cve_references,
    get_cve_references,
    upsert_cve_weaknesses,
    get_cve_weaknesses,
)


# ---------------------------------------------------------------------------
# Fixture loading helpers
# ---------------------------------------------------------------------------

FIXTURES_DIR = Path(__file__).parent / "fixtures" / "vuln_intelligence"


def load_fixture(name: str) -> dict:
    path = FIXTURES_DIR / name
    if path.suffix == ".csv":
        return {"raw": path.read_text(encoding="utf-8")}
    return json.loads(path.read_text(encoding="utf-8"))


@pytest.fixture(autouse=True)
def clean_vuln_tables():
    """Truncate all vuln intelligence tables before each test for isolation."""
    with get_db_connection() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                UPDATE sync_state SET
                    cursor_value = NULL,
                    last_successful_at = NULL,
                    last_attempted_at = NULL,
                    last_error = NULL,
                    last_snapshot_id = NULL,
                    last_good_snapshot_id = NULL,
                    consecutive_failures = 0,
                    is_healthy = TRUE;
                DELETE FROM cve_weaknesses;
                DELETE FROM cve_references;
                DELETE FROM osv_aliases;
                DELETE FROM osv_records;
                DELETE FROM cve_adp_entries;
                DELETE FROM cve_affected;
                DELETE FROM cve_relationships;
                DELETE FROM cvss_assessments;
                DELETE FROM kev_entries;
                DELETE FROM epss_scores;
                DELETE FROM source_artifacts;
                DELETE FROM vuln_source_records;
                DELETE FROM canonical_vulnerabilities;
                DELETE FROM sync_snapshots;
                INSERT INTO sync_state (source) VALUES
                    ('cve'), ('nvd'), ('kev'), ('epss'), ('osv')
                ON CONFLICT (source) DO UPDATE SET
                    cursor_value = NULL,
                    last_successful_at = NULL,
                    last_attempted_at = NULL,
                    last_error = NULL,
                    last_snapshot_id = NULL,
                    last_good_snapshot_id = NULL,
                    consecutive_failures = 0,
                    is_healthy = TRUE;
            """)
        conn.commit()
    yield


# ===========================================================================
# 1. CVE ID Validation (pure, no DB)
# ===========================================================================

class TestCveIdValidation:
    """CVE IDs are syntax-validated and never generated by Tempris."""

    def test_valid_cve_ids(self):
        assert validate_cve_id("CVE-2024-1234") is True
        assert validate_cve_id("CVE-1999-0001") is True
        assert validate_cve_id("CVE-2024-12345678") is True  # 8-digit seq OK

    def test_invalid_cve_ids(self):
        assert validate_cve_id("CVE-INVALID") is False
        assert validate_cve_id("CVE-2024-123") is False      # too short seq
        assert validate_cve_id("cve-2024-1234") is False     # lowercase
        assert validate_cve_id("CVE-24-1234") is False       # 2-digit year
        assert validate_cve_id("") is False
        assert validate_cve_id("GHSA-xxxx-yyyy-zzzz") is False
        assert validate_cve_id("CVE2024-1234") is False      # missing dash

    def test_malformed_cve_fixture_rejected(self):
        fixture = load_fixture("cve_malformed.json")
        cve_id = fixture["cveMetadata"]["cveId"]
        assert validate_cve_id(cve_id) is False


# ===========================================================================
# 2. Identity, Lifecycle, Exact-Link Semantics (rubric weight 20)
# ===========================================================================

class TestIdentityAndLifecycle:
    """PUBLISHED, RESERVED, REJECTED remain lifecycle states."""

    def test_published_cve_persisted(self):
        fixture = load_fixture("cve_published.json")
        meta = fixture["cveMetadata"]
        with get_db_connection() as conn:
            vuln = upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id=meta["cveId"],
                state=meta["state"],
                date_published=datetime.fromisoformat(meta["datePublished"].rstrip("Z")),
                date_updated=datetime.fromisoformat(meta["dateUpdated"].rstrip("Z")),
                date_reserved=datetime.fromisoformat(meta["dateReserved"].rstrip("Z")),
                assigner_org_id=meta["assignerOrgId"],
                assigner_short_name=meta["assignerShortName"],
            ))
            conn.commit()

            stored = get_canonical_vulnerability(conn, "CVE-2024-1234")
            assert stored is not None
            assert stored.cve_id == "CVE-2024-1234"
            assert stored.state == "PUBLISHED"
            assert stored.assigner_short_name == "example-cna"

    def test_reserved_cve_persisted(self):
        fixture = load_fixture("cve_reserved.json")
        meta = fixture["cveMetadata"]
        with get_db_connection() as conn:
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id=meta["cveId"],
                state=meta["state"],
                date_reserved=datetime.fromisoformat(meta["dateReserved"].rstrip("Z")),
                assigner_org_id=meta["assignerOrgId"],
                assigner_short_name=meta["assignerShortName"],
            ))
            conn.commit()

            stored = get_canonical_vulnerability(conn, "CVE-2024-9999")
            assert stored is not None
            assert stored.state == "RESERVED"
            assert stored.date_published is None  # RESERVED has no publish date

    def test_rejected_cve_with_replacement(self):
        fixture = load_fixture("cve_rejected.json")
        meta = fixture["cveMetadata"]
        cna = fixture["containers"]["cna"]
        with get_db_connection() as conn:
            # First create the CVE
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id=meta["cveId"],
                state=meta["state"],
                date_published=datetime.fromisoformat(meta["datePublished"].rstrip("Z")),
                date_rejected=datetime.fromisoformat(meta["dateRejected"].rstrip("Z")),
                date_reserved=datetime.fromisoformat(meta["dateReserved"].rstrip("Z")),
                assigner_org_id=meta["assignerOrgId"],
                assigner_short_name=meta["assignerShortName"],
            ))
            conn.commit()

            stored = get_canonical_vulnerability(conn, "CVE-2023-0001")
            assert stored is not None
            assert stored.state == "REJECTED"
            assert stored.date_rejected is not None

            # Store the replacement relationship
            for replacement in cna.get("replacedBy", []):
                upsert_cve_relationship(conn, CveRelationship(
                    cve_id=meta["cveId"],
                    related_cve_id=replacement,
                    relationship_type="replaced_by",
                    source="cve",
                ))
            conn.commit()

            rels = get_cve_relationships(conn, "CVE-2023-0001")
            assert len(rels) == 1
            assert rels[0].related_cve_id == "CVE-2023-0002"
            assert rels[0].relationship_type == "replaced_by"
            assert rels[0].source == "cve"

    def test_malformed_cve_rejected_by_repository(self):
        """A malformed CVE ID must not be inserted into canonical_vulnerabilities."""
        fixture = load_fixture("cve_malformed.json")
        meta = fixture["cveMetadata"]
        with get_db_connection() as conn:
            with pytest.raises(ValueError, match="Invalid CVE ID syntax"):
                upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                    cve_id=meta["cveId"],
                    state=meta["state"],
                ))

    def test_absence_from_incremental_is_not_deletion(self):
        """
        Absence from an incremental response is never deletion.
        A CVE that exists but is not present in a new batch must remain.
        """
        with get_db_connection() as conn:
            # Insert two CVEs
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-1234", state="PUBLISHED"))
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-5678", state="PUBLISHED"))
            conn.commit()

            # Simulate incremental batch that only mentions CVE-2024-1234
            # (CVE-2024-5678 absent — must NOT be deleted)
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-1234", state="PUBLISHED"))
            conn.commit()

            # CVE-2024-5678 must still exist
            still_exists = get_canonical_vulnerability(conn, "CVE-2024-5678")
            assert still_exists is not None
            assert still_exists.state == "PUBLISHED"


# ===========================================================================
# 3. Provenance and Multi-Assessment Preservation (rubric weight 15)
# ===========================================================================

class TestProvenanceAndMultiAssessment:
    """
    Independent raw revisions and normalized facts remain attributable.
    Multiple CVSS assessments coexist; no score overwrites another.
    """

    def test_source_record_provenance(self):
        """Each source record carries source, content hash, raw payload."""
        fixture = load_fixture("cve_published.json")
        with get_db_connection() as conn:
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-1234", state="PUBLISHED",
                assigner_org_id="f0f0f0f0-f0f0-f0f0-f0f0-f0f0f0f0f0f0",
                assigner_short_name="example-cna",
            ))
            rec, is_new = upsert_source_record(conn, SourceRecord(
                source="cve",
                source_id="CVE-2024-1234",
                cve_id="CVE-2024-1234",
                raw_payload=fixture,
            ))
            conn.commit()

            assert is_new is True
            assert rec.content_hash  # non-empty SHA-256
            assert rec.source == "cve"
            assert rec.source_id == "CVE-2024-1234"
            assert rec.is_current is True

    def test_nvd_and_cve_assessments_coexist(self):
        """
        CVE CNA and NVD independently assess CVSS. Both must coexist.
        The NVD score (9.1) must NOT overwrite the CNA score (9.8).
        """
        with get_db_connection() as conn:
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-1234", state="PUBLISHED",
                assigner_org_id="f0f0f0f0-f0f0-f0f0-f0f0-f0f0f0f0f0f0",
                assigner_short_name="example-cna",
            ))

            # CNA assessment from CVE source
            upsert_cvss_assessment(conn, CvssAssessment(
                cve_id="CVE-2024-1234",
                source="cve",
                assessor="example-cna",
                assessment_type="cna",
                cvss_version="3.1",
                vector_string="CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                base_score=Decimal("9.8"),
                base_severity="CRITICAL",
                scenario="GENERAL",
            ))

            # NVD assessment
            upsert_cvss_assessment(conn, CvssAssessment(
                cve_id="CVE-2024-1234",
                source="nvd",
                assessor="nvd@nist.gov",
                assessment_type="Primary",
                cvss_version="3.1",
                vector_string="CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
                base_score=Decimal("9.1"),
                base_severity="CRITICAL",
                exploitability_score=Decimal("3.9"),
                impact_score=Decimal("5.2"),
                scenario="GENERAL",
            ))

            # NVD CVSS 2.0 assessment (additional, not a replacement)
            upsert_cvss_assessment(conn, CvssAssessment(
                cve_id="CVE-2024-1234",
                source="nvd",
                assessor="nvd@nist.gov",
                assessment_type="Primary",
                cvss_version="2.0",
                vector_string="AV:N/AC:L/Au:N/C:C/I:C/A:N",
                base_score=Decimal("9.4"),
                scenario="GENERAL",
            ))
            conn.commit()

            assessments = get_cvss_assessments(conn, "CVE-2024-1234")
            assert len(assessments) == 3

            # Verify all three coexist with correct scores
            scores_by_key = {
                (a.assessor, a.cvss_version): a.base_score
                for a in assessments
            }
            assert scores_by_key[("example-cna", "3.1")] == Decimal("9.8")
            assert scores_by_key[("nvd@nist.gov", "3.1")] == Decimal("9.1")
            assert scores_by_key[("nvd@nist.gov", "2.0")] == Decimal("9.4")

    def test_multi_cvss_version_from_single_cve(self):
        """CVE with both CVSS 3.1 and 4.0 — both preserved, no conversion."""
        fixture = load_fixture("cve_multi_cvss.json")
        with get_db_connection() as conn:
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-5678", state="PUBLISHED",
                assigner_org_id="c3c3c3c3-c3c3-c3c3-c3c3-c3c3c3c3c3c3",
                assigner_short_name="multi-cvss-cna",
            ))

            upsert_cvss_assessment(conn, CvssAssessment(
                cve_id="CVE-2024-5678",
                source="cve",
                assessor="multi-cvss-cna",
                cvss_version="3.1",
                vector_string="CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
                base_score=Decimal("7.5"),
                base_severity="HIGH",
                scenario="GENERAL",
            ))
            upsert_cvss_assessment(conn, CvssAssessment(
                cve_id="CVE-2024-5678",
                source="cve",
                assessor="multi-cvss-cna",
                cvss_version="4.0",
                vector_string="CVSS:4.0/AV:N/AC:H/AT:N/PR:N/UI:P/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N",
                base_score=Decimal("8.3"),
                base_severity="HIGH",
                scenario="GENERAL",
            ))
            conn.commit()

            assessments = get_cvss_assessments(conn, "CVE-2024-5678")
            assert len(assessments) == 2
            versions = {a.cvss_version for a in assessments}
            assert versions == {"3.1", "4.0"}
            # No conversion: 4.0 score (8.3) is NOT treated as a 3.1 value
            for a in assessments:
                if a.cvss_version == "4.0":
                    assert a.base_score == Decimal("8.3")
                elif a.cvss_version == "3.1":
                    assert a.base_score == Decimal("7.5")

    def test_cna_and_nvd_secondary_both_preserved(self):
        """NVD Secondary assessment (CNA-originated) coexists with NVD Primary."""
        nvd = load_fixture("nvd_response.json")
        cve_data = nvd["vulnerabilities"][0]["cve"]
        metrics = cve_data["metrics"]["cvssMetricV31"]

        with get_db_connection() as conn:
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-1234", state="PUBLISHED",
                assigner_org_id="f0f0f0f0-f0f0-f0f0-f0f0-f0f0f0f0f0f0",
                assigner_short_name="example-cna",
            ))

            for m in metrics:
                upsert_cvss_assessment(conn, CvssAssessment(
                    cve_id="CVE-2024-1234",
                    source="nvd",
                    assessor=m["source"],
                    assessment_type=m["type"],
                    cvss_version=m["cvssData"]["version"],
                    vector_string=m["cvssData"]["vectorString"],
                    base_score=Decimal(str(m["cvssData"]["baseScore"])),
                    base_severity=m["cvssData"].get("baseSeverity"),
                    exploitability_score=Decimal(str(m.get("exploitabilityScore", 0))) if m.get("exploitabilityScore") else None,
                    impact_score=Decimal(str(m.get("impactScore", 0))) if m.get("impactScore") else None,
                    scenario="GENERAL",
                ))
            conn.commit()

            assessments = get_cvss_assessments(conn, "CVE-2024-1234")
            assert len(assessments) == 2
            types = {a.assessment_type for a in assessments}
            assert "Primary" in types
            assert "Secondary" in types


# ===========================================================================
# 4. CVSS / TES Resolver Correctness (rubric weight 15)
# ===========================================================================

class TestTesResolver:
    """
    Deterministic TES-input resolver:
      Tier 1: unambiguous current GENERAL Base CVSS 3.1 from assigning CNA
      Tier 2: unambiguous current GENERAL Base CVSS 3.1 from NVD/NIST
      Else:   unscoreable
    """

    def test_tier1_cna_resolution(self):
        """When CNA has exactly one CVSS 3.1 GENERAL assessment → use it."""
        with get_db_connection() as conn:
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-1234", state="PUBLISHED",
                assigner_org_id="f0f0f0f0-f0f0-f0f0-f0f0-f0f0f0f0f0f0",
                assigner_short_name="example-cna",
            ))
            upsert_cvss_assessment(conn, CvssAssessment(
                cve_id="CVE-2024-1234", source="cve",
                assessor="example-cna", cvss_version="3.1",
                vector_string="CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                base_score=Decimal("9.8"), base_severity="CRITICAL",
                scenario="GENERAL",
            ))
            # Also add NVD — should be ignored when CNA exists
            upsert_cvss_assessment(conn, CvssAssessment(
                cve_id="CVE-2024-1234", source="nvd",
                assessor="nvd@nist.gov", cvss_version="3.1",
                vector_string="CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
                base_score=Decimal("9.1"), base_severity="CRITICAL",
                scenario="GENERAL",
            ))
            conn.commit()

            res = resolve_tes_cvss(conn, "CVE-2024-1234")
            assert res.resolution_tier == "cna"
            assert res.resolved_score == Decimal("9.8")
            assert res.resolved_assessor == "example-cna"
            assert res.unscoreable_reason is None

    def test_tier2_nvd_fallback(self):
        """When no CNA CVSS 3.1 but NVD has one → use NVD."""
        with get_db_connection() as conn:
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-1234", state="PUBLISHED",
                assigner_org_id="f0f0f0f0-f0f0-f0f0-f0f0-f0f0f0f0f0f0",
                assigner_short_name="example-cna",
            ))
            # Only NVD assessment (no CNA 3.1)
            upsert_cvss_assessment(conn, CvssAssessment(
                cve_id="CVE-2024-1234", source="nvd",
                assessor="nvd@nist.gov", cvss_version="3.1",
                vector_string="CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
                base_score=Decimal("9.1"), base_severity="CRITICAL",
                scenario="GENERAL",
            ))
            conn.commit()

            res = resolve_tes_cvss(conn, "CVE-2024-1234")
            assert res.resolution_tier == "nvd"
            assert res.resolved_score == Decimal("9.1")
            assert res.resolved_assessor == "nvd@nist.gov"

    def test_unscoreable_no_31(self):
        """Only CVSS 4.0 available → unscoreable (no version conversion)."""
        with get_db_connection() as conn:
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-5678", state="PUBLISHED",
                assigner_org_id="c3c3c3c3-c3c3-c3c3-c3c3-c3c3c3c3c3c3",
                assigner_short_name="multi-cvss-cna",
            ))
            upsert_cvss_assessment(conn, CvssAssessment(
                cve_id="CVE-2024-5678", source="cve",
                assessor="multi-cvss-cna", cvss_version="4.0",
                vector_string="CVSS:4.0/AV:N/AC:H/AT:N/PR:N/UI:P/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N",
                base_score=Decimal("8.3"), base_severity="HIGH",
                scenario="GENERAL",
            ))
            conn.commit()

            res = resolve_tes_cvss(conn, "CVE-2024-5678")
            assert res.unscoreable_reason is not None
            assert res.resolved_score is None
            assert res.resolution_tier is None

    def test_unscoreable_ambiguous_cna(self):
        """Two CNA CVSS 3.1 assessments → ambiguous → unscoreable."""
        with get_db_connection() as conn:
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-1234", state="PUBLISHED",
                assigner_org_id="example-cna",
                assigner_short_name="example-cna",
            ))
            # Two different CNA assessments (different vectors but same key match)
            upsert_cvss_assessment(conn, CvssAssessment(
                cve_id="CVE-2024-1234", source="cve",
                assessor="example-cna", cvss_version="3.1",
                vector_string="CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                base_score=Decimal("9.8"), scenario="GENERAL",
            ))
            # This second one has same assessor but the unique index
            # retires the first — so only one current remains.
            # To test ambiguity, we need two distinct assessors that both match CNA.
            conn.commit()

            # Actually, the unique index ensures only one current per
            # (cve, assessor, version, scenario). Ambiguity arises when
            # the assigner matches multiple assessors. Test with org_id + short_name:
            # Reset and try with two assessors both matching CNA identifiers
            with conn.cursor() as cur:
                cur.execute("DELETE FROM cvss_assessments;")
                cur.execute("DELETE FROM canonical_vulnerabilities;")
            conn.commit()

            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-1234", state="PUBLISHED",
                assigner_org_id="example-cna-org",
                assigner_short_name="example-cna",
            ))
            # Assessor matches via org_id
            upsert_cvss_assessment(conn, CvssAssessment(
                cve_id="CVE-2024-1234", source="cve",
                assessor="example-cna-org", cvss_version="3.1",
                vector_string="CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                base_score=Decimal("9.8"), scenario="GENERAL",
            ))
            # Assessor matches via short_name
            upsert_cvss_assessment(conn, CvssAssessment(
                cve_id="CVE-2024-1234", source="cve",
                assessor="example-cna", cvss_version="3.1",
                vector_string="CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                base_score=Decimal("8.8"), scenario="GENERAL",
            ))
            conn.commit()

            res = resolve_tes_cvss(conn, "CVE-2024-1234")
            assert res.unscoreable_reason is not None
            assert "Ambiguous" in res.unscoreable_reason

    def test_unscoreable_cve_not_found(self):
        with get_db_connection() as conn:
            res = resolve_tes_cvss(conn, "CVE-9999-0001")
            assert res.unscoreable_reason == "CVE not found"

    def test_cvss_20_30_not_used_for_tes(self):
        """CVSS 2.0 and 3.0 are available evidence but NOT TES inputs."""
        with get_db_connection() as conn:
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-1234", state="PUBLISHED",
                assigner_org_id="example-cna",
                assigner_short_name="example-cna",
            ))
            # Only CVSS 2.0 and 3.0 — no 3.1
            upsert_cvss_assessment(conn, CvssAssessment(
                cve_id="CVE-2024-1234", source="nvd",
                assessor="nvd@nist.gov", cvss_version="2.0",
                vector_string="AV:N/AC:L/Au:N/C:C/I:C/A:N",
                base_score=Decimal("9.4"), scenario="GENERAL",
            ))
            upsert_cvss_assessment(conn, CvssAssessment(
                cve_id="CVE-2024-1234", source="nvd",
                assessor="nvd@nist.gov", cvss_version="3.0",
                vector_string="CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
                base_score=Decimal("9.1"), scenario="GENERAL",
            ))
            conn.commit()

            res = resolve_tes_cvss(conn, "CVE-2024-1234")
            assert res.unscoreable_reason is not None
            assert res.resolved_score is None


# ===========================================================================
# 5. Atomic Synchronization and Idempotency (rubric weight 20)
# ===========================================================================

class TestAtomicSyncAndIdempotency:
    """
    Content-addressed dedup, revision tracking, atomic current-pointer moves.
    """

    def test_content_hash_deterministic(self):
        """Same payload always produces the same hash."""
        payload = {"key": "value", "nested": {"a": 1}}
        h1 = content_hash(payload)
        h2 = content_hash(payload)
        assert h1 == h2
        # Different key order → same canonical JSON → same hash
        h3 = content_hash({"nested": {"a": 1}, "key": "value"})
        assert h1 == h3

    def test_unchanged_source_stored_once(self):
        """Importing the same content twice does not create a second revision."""
        fixture = load_fixture("cve_published.json")
        with get_db_connection() as conn:
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-1234", state="PUBLISHED"))

            rec1, is_new1 = upsert_source_record(conn, SourceRecord(
                source="cve", source_id="CVE-2024-1234",
                cve_id="CVE-2024-1234", raw_payload=fixture,
            ))
            conn.commit()

            rec2, is_new2 = upsert_source_record(conn, SourceRecord(
                source="cve", source_id="CVE-2024-1234",
                cve_id="CVE-2024-1234", raw_payload=fixture,
            ))
            conn.commit()

            assert is_new1 is True
            assert is_new2 is False  # Deduped — same content hash
            assert rec1.content_hash == rec2.content_hash

            revisions = get_source_record_revisions(conn, "cve", "CVE-2024-1234")
            assert len(revisions) == 1  # Only one revision stored

    def test_new_content_creates_revision_moves_current(self):
        """Changed content creates a new revision and moves is_current."""
        fixture_v1 = load_fixture("cve_published.json")
        fixture_v2 = load_fixture("cve_published_updated.json")
        with get_db_connection() as conn:
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-1234", state="PUBLISHED"))

            rec1, _ = upsert_source_record(conn, SourceRecord(
                source="cve", source_id="CVE-2024-1234",
                cve_id="CVE-2024-1234", raw_payload=fixture_v1,
            ))
            conn.commit()
            assert rec1.is_current is True

            rec2, is_new = upsert_source_record(conn, SourceRecord(
                source="cve", source_id="CVE-2024-1234",
                cve_id="CVE-2024-1234", raw_payload=fixture_v2,
            ))
            conn.commit()
            assert is_new is True
            assert rec1.content_hash != rec2.content_hash

            # Current pointer moved
            current = get_current_source_record(conn, "cve", "CVE-2024-1234")
            assert current is not None
            assert current.content_hash == rec2.content_hash

            # Prior revision traceable
            revisions = get_source_record_revisions(conn, "cve", "CVE-2024-1234")
            assert len(revisions) == 2
            assert revisions[0].is_current is True   # newest first
            assert revisions[1].is_current is False

    def test_snapshot_lifecycle(self):
        """Sync snapshots record provenance and activation."""
        with get_db_connection() as conn:
            snap = create_sync_snapshot(conn, SyncSnapshot(
                source="cve", sync_mode="bootstrap",
                cursor_before=None,
            ))
            conn.commit()

            assert snap.id is not None
            assert snap.status == "running"

            complete_sync_snapshot(conn, snap.id,
                status="completed",
                records_processed=100,
                records_created=95,
                records_updated=5,
                cursor_after="2024-04-15T00:00:00Z",
            )
            conn.commit()

            stored = get_sync_snapshot(conn, snap.id)
            assert stored.status == "completed"
            assert stored.records_processed == 100
            assert stored.records_created == 95
            assert stored.cursor_after == "2024-04-15T00:00:00Z"
            assert stored.completed_at is not None

    def test_sync_state_success_advances_cursor(self):
        """Successful sync advances cursor and resets failure count."""
        with get_db_connection() as conn:
            state = get_sync_state(conn, "cve")
            assert state is not None
            assert state.cursor_value is None
            assert state.is_healthy is True

            snap = create_sync_snapshot(conn, SyncSnapshot(
                source="cve", sync_mode="bootstrap"))
            conn.commit()

            updated = update_sync_state(conn, "cve",
                cursor_value="2024-04-15T00:00:00Z",
                last_snapshot_id=snap.id,
                success=True,
            )
            conn.commit()

            assert updated.cursor_value == "2024-04-15T00:00:00Z"
            assert updated.is_healthy is True
            assert updated.consecutive_failures == 0
            assert updated.last_successful_at is not None

    def test_sync_state_failure_preserves_cursor(self):
        """
        Failed sync increments failure count and marks unhealthy.
        Cursor remains unchanged — last known good active.
        """
        with get_db_connection() as conn:
            # First, establish a successful cursor
            snap1 = create_sync_snapshot(conn, SyncSnapshot(
                source="nvd", sync_mode="bootstrap"))
            conn.commit()
            update_sync_state(conn, "nvd",
                cursor_value="2024-04-15T00:00:00Z",
                last_snapshot_id=snap1.id, success=True)
            conn.commit()

            # Now simulate a failure
            snap2 = create_sync_snapshot(conn, SyncSnapshot(
                source="nvd", sync_mode="incremental"))
            conn.commit()
            state = update_sync_state(conn, "nvd",
                last_snapshot_id=snap2.id, success=False,
                error="Connection timeout")
            conn.commit()

            assert state.cursor_value == "2024-04-15T00:00:00Z"  # unchanged!
            assert state.is_healthy is False
            assert state.consecutive_failures == 1
            assert state.last_error == "Connection timeout"

    def test_one_source_failure_does_not_block_others(self):
        """Source isolation: NVD failure doesn't affect KEV health."""
        with get_db_connection() as conn:
            # Fail NVD
            snap_nvd = create_sync_snapshot(conn, SyncSnapshot(
                source="nvd", sync_mode="incremental"))
            conn.commit()
            update_sync_state(conn, "nvd",
                last_snapshot_id=snap_nvd.id, success=False,
                error="NVD API 503")
            conn.commit()

            # Succeed KEV
            snap_kev = create_sync_snapshot(conn, SyncSnapshot(
                source="kev", sync_mode="incremental"))
            conn.commit()
            update_sync_state(conn, "kev",
                cursor_value="2024.04.15",
                last_snapshot_id=snap_kev.id, success=True)
            conn.commit()

            nvd_state = get_sync_state(conn, "nvd")
            kev_state = get_sync_state(conn, "kev")
            assert nvd_state.is_healthy is False
            assert kev_state.is_healthy is True
            assert kev_state.cursor_value == "2024.04.15"

    def test_all_five_sync_states_seeded(self):
        """Migration seeds sync_state rows for cve, nvd, kev, epss, osv."""
        with get_db_connection() as conn:
            states = get_all_sync_states(conn)
            sources = {s.source for s in states}
            assert sources == {"cve", "nvd", "kev", "epss", "osv"}


# ===========================================================================
# 6. KEV and EPSS Enrichment
# ===========================================================================

class TestKevAndEpss:
    """KEV and EPSS are enrichment, not tenant Finding or exposure state."""

    def test_kev_entry_from_fixture(self):
        fixture = load_fixture("kev_catalog.json")
        with get_db_connection() as conn:
            for v in fixture["vulnerabilities"]:
                upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                    cve_id=v["cveID"], state="PUBLISHED"))

            for v in fixture["vulnerabilities"]:
                upsert_kev_entry(conn, KevEntry(
                    cve_id=v["cveID"],
                    vendor_project=v["vendorProject"],
                    product=v["product"],
                    vulnerability_name=v["vulnerabilityName"],
                    date_added=date.fromisoformat(v["dateAdded"]),
                    short_description=v["shortDescription"],
                    required_action=v["requiredAction"],
                    due_date=date.fromisoformat(v["dueDate"]),
                    known_ransomware=v["knownRansomwareCampaignUse"],
                    notes=v.get("notes"),
                ))
            conn.commit()

            kev = get_kev_entry(conn, "CVE-2024-1234")
            assert kev is not None
            assert kev.known_ransomware == "Known"
            assert kev.vendor_project == "Example Corp"

            kev2 = get_kev_entry(conn, "CVE-2024-5678")
            assert kev2 is not None
            assert kev2.known_ransomware == "Unknown"

    def test_kev_upsert_idempotent(self):
        """Re-importing the same KEV entry updates without duplicating."""
        with get_db_connection() as conn:
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-1234", state="PUBLISHED"))
            upsert_kev_entry(conn, KevEntry(
                cve_id="CVE-2024-1234", vendor_project="V1",
                product="P1", vulnerability_name="N1",
                date_added=date(2024, 4, 1),
            ))
            conn.commit()
            upsert_kev_entry(conn, KevEntry(
                cve_id="CVE-2024-1234", vendor_project="V1-Updated",
                product="P1", vulnerability_name="N1",
                date_added=date(2024, 4, 1),
            ))
            conn.commit()

            kev = get_kev_entry(conn, "CVE-2024-1234")
            assert kev.vendor_project == "V1-Updated"

    def test_epss_daily_history(self):
        """EPSS scores maintain daily history per CVE."""
        with get_db_connection() as conn:
            upsert_epss_score(conn, EpssScore(
                cve_id="CVE-2024-1234", score=Decimal("0.95432"),
                percentile=Decimal("0.99100"), model_version="v2024.03.01",
                score_date=date(2024, 4, 15),
            ))
            upsert_epss_score(conn, EpssScore(
                cve_id="CVE-2024-1234", score=Decimal("0.96000"),
                percentile=Decimal("0.99200"), model_version="v2024.03.01",
                score_date=date(2024, 4, 16),
            ))
            conn.commit()

            history = get_epss_scores(conn, "CVE-2024-1234")
            assert len(history) == 2
            # Most recent first
            assert history[0].score_date == date(2024, 4, 16)
            assert history[0].score == Decimal("0.96000")
            assert history[1].score_date == date(2024, 4, 15)

            latest = get_epss_scores(conn, "CVE-2024-1234", latest_only=True)
            assert len(latest) == 1
            assert latest[0].score == Decimal("0.96000")


# ===========================================================================
# 7. OSV Identity and Alias Separation
# ===========================================================================

class TestOsvIdentityAndAliases:
    """
    OSV identities remain OSV identities. aliases, related, and upstream
    remain distinct. Only an exact declared CVE-* alias links to the CVE spine.
    """

    def test_osv_with_cve_alias_linked(self):
        """GHSA with exact CVE alias → linked to CVE spine."""
        fixture = load_fixture("osv_ghsa.json")
        with get_db_connection() as conn:
            # Create the CVE first
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-1234", state="PUBLISHED"))

            osv = upsert_osv_record(conn, OsvRecord(
                osv_id=fixture["id"],
                summary=fixture["summary"],
                details=fixture["details"],
                published=datetime.fromisoformat(fixture["published"].rstrip("Z")),
                modified=datetime.fromisoformat(fixture["modified"].rstrip("Z")),
                ecosystem=fixture["affected"][0]["package"]["ecosystem"],
                package_name=fixture["affected"][0]["package"]["name"],
                package_purl=fixture["affected"][0]["package"].get("purl"),
                affected_ranges=fixture["affected"],
                severity=fixture.get("severity"),
                database_specific=fixture.get("database_specific"),
                references=fixture.get("references"),
                raw_payload=fixture,
                schema_version=fixture.get("schema_version"),
            ))
            conn.commit()

            # Process aliases
            for alias_val in fixture.get("aliases", []):
                linked_cve = alias_val if validate_cve_id(alias_val) else None
                upsert_osv_alias(conn, OsvAlias(
                    osv_id=fixture["id"],
                    alias=alias_val,
                    alias_type="alias",
                    linked_cve_id=linked_cve,
                ))
            # Process related (distinct from aliases!)
            for related_val in fixture.get("related", []):
                linked_cve = related_val if validate_cve_id(related_val) else None
                upsert_osv_alias(conn, OsvAlias(
                    osv_id=fixture["id"],
                    alias=related_val,
                    alias_type="related",
                    linked_cve_id=linked_cve,
                ))
            conn.commit()

            # Verify OSV record stored with native identity
            stored = get_osv_record(conn, "GHSA-xxxx-yyyy-zzzz")
            assert stored is not None
            assert stored.osv_id == "GHSA-xxxx-yyyy-zzzz"
            assert stored.ecosystem == "PyPI"
            assert stored.package_name == "example-package"

            # Verify alias linkage
            aliases = get_osv_aliases(conn, "GHSA-xxxx-yyyy-zzzz")
            cve_aliases = [a for a in aliases if a.alias_type == "alias" and a.linked_cve_id]
            related = [a for a in aliases if a.alias_type == "related"]
            assert len(cve_aliases) == 1
            assert cve_aliases[0].linked_cve_id == "CVE-2024-1234"
            assert len(related) == 1
            assert related[0].alias == "GHSA-aaaa-bbbb-cccc"
            assert related[0].linked_cve_id is None  # not a CVE → no link

            # Reverse lookup: CVE → OSV
            linked_osv = get_osv_records_by_cve(conn, "CVE-2024-1234")
            assert len(linked_osv) == 1
            assert linked_osv[0].osv_id == "GHSA-xxxx-yyyy-zzzz"

    def test_osv_without_cve_no_spine_link(self):
        """OSV without any CVE alias → no link to CVE spine."""
        fixture = load_fixture("osv_no_cve.json")
        with get_db_connection() as conn:
            upsert_osv_record(conn, OsvRecord(
                osv_id=fixture["id"],
                summary=fixture["summary"],
                ecosystem=fixture["affected"][0]["package"]["ecosystem"],
                package_name=fixture["affected"][0]["package"]["name"],
                raw_payload=fixture,
            ))
            # No aliases have CVE IDs
            for alias_val in fixture.get("aliases", []):
                linked_cve = alias_val if validate_cve_id(alias_val) else None
                upsert_osv_alias(conn, OsvAlias(
                    osv_id=fixture["id"],
                    alias=alias_val,
                    alias_type="alias",
                    linked_cve_id=linked_cve,
                ))
            for related_val in fixture.get("related", []):
                linked_cve = related_val if validate_cve_id(related_val) else None
                upsert_osv_alias(conn, OsvAlias(
                    osv_id=fixture["id"],
                    alias=related_val,
                    alias_type="related",
                    linked_cve_id=linked_cve,
                ))
            conn.commit()

            stored = get_osv_record(conn, "GHSA-no-cve-link")
            assert stored is not None
            assert stored.ecosystem == "npm"

            aliases = get_osv_aliases(conn, "GHSA-no-cve-link")
            # related entries exist but none link to CVE spine
            cve_linked = [a for a in aliases if a.linked_cve_id is not None]
            assert len(cve_linked) == 0

    def test_osv_withdrawn_state_preserved(self):
        """Explicit withdrawn state is retained as upstream state."""
        fixture = load_fixture("osv_withdrawn.json")
        with get_db_connection() as conn:
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-1234", state="PUBLISHED"))
            upsert_osv_record(conn, OsvRecord(
                osv_id=fixture["id"],
                summary=fixture["summary"],
                withdrawn=datetime.fromisoformat(fixture["withdrawn"].rstrip("Z")),
                raw_payload=fixture,
            ))
            conn.commit()

            stored = get_osv_record(conn, "PYSEC-2024-100")
            assert stored is not None
            assert stored.withdrawn is not None

    def test_related_alone_does_not_link_to_cve(self):
        """
        Product/title similarity or a non-alias reference must NOT create
        a CVE association. Only exact declared CVE-* alias links.
        """
        with get_db_connection() as conn:
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-1234", state="PUBLISHED"))
            upsert_osv_record(conn, OsvRecord(
                osv_id="GHSA-related-only",
                summary="Related but not aliased to CVE-2024-1234",
                raw_payload={"id": "GHSA-related-only"},
            ))
            # Only a 'related' link, not an 'alias'
            upsert_osv_alias(conn, OsvAlias(
                osv_id="GHSA-related-only",
                alias="CVE-2024-1234",
                alias_type="related",
                linked_cve_id=None,  # related → no spine link!
            ))
            conn.commit()

            # get_osv_records_by_cve only follows alias links, not related
            linked = get_osv_records_by_cve(conn, "CVE-2024-1234")
            assert len(linked) == 0


# ===========================================================================
# 8. ADP / SSVC Enrichment
# ===========================================================================

class TestAdpSsvc:
    """ADP and SSVC data carried through CVE ingestion."""

    def test_adp_entry_with_ssvc(self):
        fixture = load_fixture("cve_published.json")
        adp_container = fixture["containers"]["adp"][0]
        ssvc_metric = adp_container["metrics"][0]["other"]

        with get_db_connection() as conn:
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-1234", state="PUBLISHED"))

            upsert_adp_entry(conn, CveAdpEntry(
                cve_id="CVE-2024-1234",
                provider_org_id=adp_container["providerMetadata"]["orgId"],
                provider_short_name=adp_container["providerMetadata"]["shortName"],
                date_updated=datetime.fromisoformat(
                    adp_container["providerMetadata"]["dateUpdated"].rstrip("Z")),
                title=adp_container.get("title"),
                ssvc_data=ssvc_metric.get("content"),
                raw_data=adp_container,
            ))
            conn.commit()

            entries = get_adp_entries(conn, "CVE-2024-1234")
            assert len(entries) == 1
            assert entries[0].provider_short_name == "CISA-ADP"
            assert entries[0].ssvc_data is not None
            assert entries[0].ssvc_data["role"] == "CISA Coordinator"


# ===========================================================================
# 9. CVE Affected Products
# ===========================================================================

class TestCveAffected:
    """Affected/applicability data from CNA and NVD sources."""

    def test_affected_from_cve_fixture(self):
        fixture = load_fixture("cve_published.json")
        affected_data = fixture["containers"]["cna"]["affected"][0]

        with get_db_connection() as conn:
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-1234", state="PUBLISHED"))

            upsert_cve_affected(conn, CveAffected(
                cve_id="CVE-2024-1234",
                source="cve",
                vendor=affected_data["vendor"],
                product=affected_data["product"],
                versions=affected_data["versions"],
                default_status=affected_data.get("defaultStatus"),
                raw_data=affected_data,
            ))
            conn.commit()

            stored = get_cve_affected(conn, "CVE-2024-1234")
            assert len(stored) == 1
            assert stored[0].vendor == "Example Corp"
            assert stored[0].product == "Example Product"
            assert stored[0].default_status == "unaffected"


# ===========================================================================
# 10. References and Weaknesses
# ===========================================================================

class TestReferencesAndWeaknesses:
    def test_references_from_cve(self):
        fixture = load_fixture("cve_published.json")
        refs = fixture["containers"]["cna"]["references"]

        with get_db_connection() as conn:
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-1234", state="PUBLISHED"))
            count = upsert_cve_references(conn, "CVE-2024-1234", "cve", refs)
            conn.commit()

            assert count == 1
            stored = get_cve_references(conn, "CVE-2024-1234")
            assert len(stored) == 1
            assert "example.com" in stored[0]["url"]

    def test_weaknesses_from_cve(self):
        fixture = load_fixture("cve_published.json")
        problems = fixture["containers"]["cna"]["problemTypes"]

        with get_db_connection() as conn:
            upsert_canonical_vulnerability(conn, CanonicalVulnerability(
                cve_id="CVE-2024-1234", state="PUBLISHED"))
            weaknesses = []
            for pt in problems:
                for desc in pt["descriptions"]:
                    weaknesses.append({
                        "cwe_id": desc.get("cweId"),
                        "description": desc.get("description"),
                        "type": desc.get("type"),
                    })
            count = upsert_cve_weaknesses(conn, "CVE-2024-1234", "cve", weaknesses)
            conn.commit()

            assert count == 1
            stored = get_cve_weaknesses(conn, "CVE-2024-1234")
            assert len(stored) == 1
            assert stored[0]["cwe_id"] == "CWE-89"


# ===========================================================================
# 11. No Tenant State in Public Tables
# ===========================================================================

class TestNoTenantState:
    """Public intelligence tables contain no tenant IDs."""

    def test_canonical_vulnerabilities_has_no_tenant_id(self):
        with get_db_connection() as conn:
            with conn.cursor() as cur:
                cur.execute("""
                    SELECT column_name FROM information_schema.columns
                    WHERE table_name = 'canonical_vulnerabilities'
                    AND column_name = 'tenant_id';
                """)
                assert cur.fetchone() is None

    def test_vuln_source_records_has_no_tenant_id(self):
        with get_db_connection() as conn:
            with conn.cursor() as cur:
                cur.execute("""
                    SELECT column_name FROM information_schema.columns
                    WHERE table_name = 'vuln_source_records'
                    AND column_name = 'tenant_id';
                """)
                assert cur.fetchone() is None

    def test_kev_entries_has_no_tenant_id(self):
        with get_db_connection() as conn:
            with conn.cursor() as cur:
                cur.execute("""
                    SELECT column_name FROM information_schema.columns
                    WHERE table_name = 'kev_entries'
                    AND column_name = 'tenant_id';
                """)
                assert cur.fetchone() is None

    def test_epss_scores_has_no_tenant_id(self):
        with get_db_connection() as conn:
            with conn.cursor() as cur:
                cur.execute("""
                    SELECT column_name FROM information_schema.columns
                    WHERE table_name = 'epss_scores'
                    AND column_name = 'tenant_id';
                """)
                assert cur.fetchone() is None

    def test_osv_records_has_no_tenant_id(self):
        with get_db_connection() as conn:
            with conn.cursor() as cur:
                cur.execute("""
                    SELECT column_name FROM information_schema.columns
                    WHERE table_name = 'osv_records'
                    AND column_name = 'tenant_id';
                """)
                assert cur.fetchone() is None


# ===========================================================================
# 12. Migration Idempotency
# ===========================================================================

class TestMigrationIdempotency:
    """Migration 007 uses CREATE TABLE IF NOT EXISTS / ON CONFLICT DO NOTHING."""

    def test_migration_007_can_run_twice(self):
        """Running the migration SQL again must not error (idempotent DDL)."""
        from pathlib import Path
        migration_path = Path(__file__).parent.parent / "migrations" / "007_vulnerability_intelligence.sql"
        sql = migration_path.read_text(encoding="utf-8")

        with get_db_connection() as conn:
            with conn.cursor() as cur:
                # The migration was already applied by the session fixture.
                # Running it again must not raise.
                cur.execute(sql)
            conn.commit()

        # Verify tables still exist
        with get_db_connection() as conn:
            with conn.cursor() as cur:
                cur.execute("""
                    SELECT table_name FROM information_schema.tables
                    WHERE table_schema = 'public'
                    AND table_name IN (
                        'canonical_vulnerabilities', 'vuln_source_records',
                        'cvss_assessments', 'cve_relationships', 'cve_affected',
                        'kev_entries', 'epss_scores', 'osv_records', 'osv_aliases',
                        'cve_adp_entries', 'sync_snapshots', 'sync_state',
                        'cve_references', 'cve_weaknesses'
                    );
                """)
                tables = {r["table_name"] for r in cur.fetchall()}

            expected = {
                "canonical_vulnerabilities", "vuln_source_records",
                "cvss_assessments", "cve_relationships", "cve_affected",
                "kev_entries", "epss_scores", "osv_records", "osv_aliases",
                "cve_adp_entries", "sync_snapshots", "sync_state",
                "cve_references", "cve_weaknesses",
            }
            assert tables == expected
